### ISSUE TITLE
Event serialization is still an issue

### ISSUE THREAD

**Issue by Kethku** [KillTheMule/nvim-rs#31]
I just encountered an example of the bugs I ran into with Neovide way back when which motivated my crappy fork to serialize events received from neovim. I think this means that the most recent serialization effort wasn't fully successful.

Unfortunately I honestly don't understand the problem fully or even know how to reproduce the issue consistently as these days its very rare.

I'm happy to help out any way I can though. It seems like something that we should be able to fix...

**Comment by KillTheMule** [comment]
Oh wow, damn! Ok, so how do we approach that... can you describe again what exactly happens when things go wrong? You're saying "bugs" rather than "bug", does it manifest in different ways? If you encounter this sometimes, my idea would be to make a branch of `nvim-rs` with extended logging that you could use with your local neovide, and whenever the problem(s) pops up again you can stop what you're doing, upload the log and we can look through it and maybe find the problem.

Sounds reasonable? Any other ideas how to go on? @Lyude any ideas from your side?

**Comment by Lyude** [comment]
> Oh wow, damn! Ok, so how do we approach that... can you describe again what exactly happens when things go wrong? You're saying "bugs" rather than "bug", does it manifest in different ways? If you encounter this sometimes, my idea would be to make a branch of `nvim-rs` with extended logging that you could use with your local neovide, and whenever the problem(s) pops up again you can stop what you're doing, upload the log and we can look through it and maybe find the problem.
> 
> Sounds reasonable? Any other ideas how to go on? @Lyude any ideas from your side?

I think this would be a good idea. IMHO it probably would also be good idea to send a PR to introduce more thorough nvim-rs logging in the main branch. I was already thinking of adding this as it seems like something we'd want readily available for anyone filling bug reports anyhow.

**Comment by Lyude** [comment]
Also - we may want to add some sort of timestamps with logging and ensure we can actually figure out the order of events that is happening.
Something else that occurred to me though @Kethku - was your fork of `nvim-rs` able to successfully mitigate those issues? I wonder if your changes might just be able to give us a good starting point to figuring out where the problem actually lies

**Comment by Kethku** [comment]
@KillTheMule this sounds like a great approach to me. I'm happy to work on it if you point me in the right direction.
@Lyude yes! My fork did fix the issue, I don't remember all the details about how it worked except that it was definitely a hack. The original diff can be found here: https://github.com/KillTheMule/nvim-rs/pull/13/files. I think it worked by pushing all notifications onto a queue and handling them in order on their own processor task.

**Comment by Kethku** [comment]
Actually I think I can maybe repro by setting up a custom event to send to neovide which is indexed (simple while loop in neovim) and then log out the order in which we get those events. If done properly I think I can get it to send the events to neovide out of order. That may be enough to repro it consistently.

**Comment by Lyude** [comment]
> @KillTheMule this sounds like a great approach to me. I'm happy to work on it if you point me in the right direction.

I threw this issue around with a few rustacean friends of mine and they suggested we consider something like https://github.com/knurling-rs/defmt so that we can record the order of events happening and print them back on a panic or other error even without having to specify any debugging options at runtime beforehand

> @Lyude yes! My fork did fix the issue, I don't remember all the details about how it worked except that it was definitely a hack. The original diff can be found here: https://github.com/KillTheMule/nvim-rs/pull/13/files. I think it worked by pushing all notifications onto a queue and handling them in order on their own processor task.

If no one else gets to this first I will try to take a look at this soon

**Comment by Lyude** [comment]
Oh - I also wonder if as a long-term TODO if we should consider https://github.com/tokio-rs/loom

**Comment by KillTheMule** [comment]
Ok, I"ve put upt https://github.com/KillTheMule/nvim-rs/tree/log, there's a bit of logging added that might help us identify the issue. Would you give it a shot, @Kethku ? Unfortunately, notifications don't carry IDs, so I hope this all works out... adding timestamps is the job of the logging provider, i.e. the application. I don't know a lot about flexi-logger, but I sure hope you can "just" add timestamps.

Yeah, loom has been on the back of my mind as well, that sounds very useful.

Not sure what defmt would help here though, it's not a problem to specify it all beforehand and wait for @Kethku to be able to reproduce the problem, I think. Or am I missing something?

Ah, side node, the patched version of nvim-rs worked, but would lock up if nesting requests, so that's not a way we can go.

**Comment by KillTheMule** [comment]
I'll be leaving this open in case someone experiences something similar. I'll just add a label.

**Comment by Kethku** [comment]
This has been fixed on our side. Apologies for the fuzzy issue and poor description.

**Comment by KillTheMule** [comment]
Great, thanks for coming back! I think I'll have some comments on the neovide issue, but good to hear this works out :)
