### ISSUE TITLE
handler_drop yields an empty txt

### ISSUE THREAD

**Issue by zjp-CN** [KillTheMule/nvim-rs#41]
When I make handler_drop example runnable on my local machine, I find 
 [handler_drop.rs](https://github.com/KillTheMule/nvim-rs/blob/327c0eb7576d0a9558cde7613835a7ab279456c2/examples/handler_drop.rs) yields an empty txt without any error, so I modified it to
[handler_drop2.rs](https://github.com/zjp-CN/nvim-rs/blob/af30b14190134d9433891a9f37c9614ca9e8b4ef/examples/handler_drop2.rs), and the new one yields what is as expected.

Main difference: comment the last one and two lines, and remove old unnecessary variables.
```RUST
  // let _ = nvim.command(&close).await;
  // let _ = io_handle.await;
```

```
$ nvim --version
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by runner@fv-az87-780
```

I can open a PR for this, if you want it.

**Comment by KillTheMule** [comment]
Huh, that's weird.

So first of all, those lines aren't strictly needed indeed, but what I consider good pratice, and they might keep you out of trouble in more complex scenarios.

Why the file is empty for you though is a mystery to me. It works out properly on my end. Did you remove the file beforehand, so there are no weird filesystem interactions? What system are you running this on?

**Comment by zjp-CN** [comment]
> What system are you running this on?

Linux version 5.4.0-86-generic (buildd@lgw01-amd64-041) (gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04))

> Did you remove the file beforehand, so there are no weird filesystem interactions?

That doesn't matter. Here is the process:
(handler_drop.txt and nvimlog do not exist in the beginning and are not removed if exist, cargo info is stripped here)
```RUST
$ cargo run --example handler_drop --features="use_tokio"
$ cat handler_drop.txt
$ cat nvimlog
$ cargo run --example handler_drop2 --features="use_tokio"
$ cat handler_drop.txt
xyz
abc
$ cat nvimlog
$ cargo run --example handler_drop2 --features="use_tokio"
$ cat handler_drop.txt
xyz
abc
$ cat nvimlog
```

**Comment by zjp-CN** [comment]
> those lines aren't strictly needed indeed, but what I consider good pratice, and they might keep you out of trouble in more complex scenarios

Fine to keep them.

BTW [scorched_earth.rs](https://github.com/KillTheMule/nvim-rs/blob/master/examples/scorched_earth.rs) and the documentation is really great, it's successful to make it run with the instructions.

**Comment by KillTheMule** [comment]
> Here is the process:

Well, that is just weird. Since I can't reproduce it, I need to ask you to debug it. Could you insert a `dbg` statement into the drop impl, and maybe also into the handler, so we can see if things happen how we expect them to?

**Comment by zjp-CN** [comment]
https://github.com/zjp-CN/nvim-rs/commit/ad7c1d1709732dd7e353ae2f1c77e7e3767f07e4

<sub>Changes only on the last two lines are recorded.</sub>

https://user-images.githubusercontent.com/25300418/160273076-08b34f20-0dfb-4408-a619-bba4fef7c9ac.mp4

**Comment by KillTheMule** [comment]
Ok, I can somewhat guess what's going on. We're asking nvim to close the channel, and after that we run out io loop. Seems that on your system nvim closes the channel faster than we handle the `nvim_buf_lines_event` notification, so that the handler data ever stays empty. Maybe on my system that stuff is just slower, so it works out in the right order.

Quick question: You are using the neovim source that's provided as a submodule, right? It might just be racy here, but if neovim somehow changed behavior, that might also be a reason.

I think the example needs "just" a more complex shutdown logic, so we don't have the channel closed on us to early. It's a bit artificial here, because we want to bail out after the first notification, but it should be as simple as moving the close command into the notification handling, after we've updated the handler.

Now the real question though: How the hell does this work if you comment out those lines? I mean, we don't really need the `chanclose` command indeed, but if nothing runs the `io_handle`, nothing will ever call the notification handler, so how the hell does the handler get the data? I'm dumbfounded...

**Comment by zjp-CN** [comment]
> You are using the neovim source that's provided as a submodule, right?

Well, no. I use the officially compiled neovim binary put in `/usr/bin/nvim` locally.

**Comment by KillTheMule** [comment]
Ahh ok. I've always wanted to switch to a downloaded binary instead of compiling neovim from source for the tests, but never got around to doing this. I'll check that out, but it doesn't seem to be the reason for what you're seeing anyways :)

**Comment by zjp-CN** [comment]
Cool, the PR https://github.com/KillTheMule/nvim-rs/pull/42 resolved this issue perfectly.
